name: LuckTimeFix
version: '${project.version}'
main: com.peckot.spigot.LuckTimeFix.LuckTimeFix
depend: [ LuckPerms ]
author: Pectics
description: To directly modify players' parent group or permission time.
website: https://peckot.com
commands:
  lucktime:
    aliases: [ lt ]
    usage: /lucktime <player> group|perm <groupName|permissionNode> add|remove <time>
    description: Modify players' parent group or permission time.
    permission: lucktimefix.admin
permissions:
  lucktimefix.admin:
    description: To directly modify players' parent group or permission time.
    default: op
